default_language_version:
  python: python3.11
default_stages: [commit]
exclude: (chapters/03-dict-set/py3.10/creator.py, chapters/03-dict-set/support)

repos:
  - repo: local
    hooks:
      - id: autoflake
        name: Remove unused variables and imports
        entry: bash -c 'autoflake "$@";' --
        language: python
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--expand-star-imports",
            "--ignore-init-module-imports",
          ]
        files: \.py$
      - id: isort
        name: Sorting import statements
        entry: bash -c 'isort "$@";' --
        language: python
        args: ["--filter-files"]
        files: \.py$
      - id: black
        name: Black Python code formatting
        entry: bash -c 'black --target-version py310 "$@";' --
        language: python
        types: [python]
        args: ["--line-length=120"]
      - id: flake8
        name: flake8
        entry: poetry run autoflake
        language: python
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        language: python
        types: [python]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: python
        types: [python]
        pass_filenames: false
